### ISSUE TITLE
Serialize closures

### ISSUE THREAD

**Issue by julian-zucker** [evvo-labs/evvo#51]
Creator, mutator, deletor, and objective functions are closures, and therefore not serializable without effort.

[SIP 21 "Spores"](https://docs.scala-lang.org/sips/spores.html) solves this, and we should use it behind-the-scenes to convert user-provided closures to Spores. Without Spores, we have to demand more of end users, which is unacceptable.

**Comment by drassaby** [comment]
https://github.com/heathermiller/spores

**Comment by julian-zucker** [comment]
Spores hasn't been maintained in 3 years and isn't built for 2.12.

Looking into https://doc.akka.io/docs/akka/current/persistence.html, but it doesn't look like what we want

**Comment by drassaby** [comment]
We could also try Scala pickling

**Comment by julian-zucker** [comment]
I'm becoming less and less convinced this is a serialization issue, at least not directly. From the [scala docs](calendar.google.com/calendar/render#main_7), if you have 
```
akka {
  actor {
    serialize-creators = on
    serialize-messages = on
  }
}
```
then everything should be getting serialized. The issue is in the types of the deserialized functions - the SerializedLambdas don't know they're supposed to conform to the type

**Comment by drassaby** [comment]
@julian-zucker and I Investigated and confirmed that the problems we're facing with function deserialization are likely due to type erasure. We did some preliminary tests, and found that if we cast creators, mutators, and deletors to type `Any`, that we can deserialize them correctly. We then need to be able to cast them back correctly. We are thinking about using a case class with two fields, the object cast to `Any` and the type to cast that object upon deserialization.
