### ISSUE TITLE
Mutators should be called Improvers or Modifiers

### ISSUE THREAD

**Issue by rachlin** [evvo-labs/evvo#90]
**Describe the refactor you'd like.**
Change the MutatorAgent / MutatorFunction classes / types to something like ImproverAgent or ModifierAgent or ChangeAgent.

**Why should the refactor happen?**
In the EvoComp literature, especially genetic algorithms, a mutation is typically a point mutation made to a single solution.  Crossover would not be considered a mutation operator, for example.  

**Additional context**

**Comment by drassaby** [comment]
I'm down to rename the Mutators to something more in line with the literature, but it would be great if we could keep it to the same number of characters as the other agents. It makes the code very easy to skim on a page. Right now we have:

```
CreatorAgent
MutatorAgent
DeletorAgent
```

@rachlin have you seen anything in the literature that would fit this pattern? We could do something like `DerivorAgent` because the agent uses the solutions it requests from the population to derive new solutions.

**Comment by rachlin** [comment]
How about CREATE, MODIFY, DELETE.  E.g. ModifyAgent.   Each is 6 letters.

**Comment by julian-zucker** [comment]
Same # of characters isn't vital. Also, we can have Mutator stick around as a one-to-one mutation operator, and add Improver as a generic base class for set-to-set changes.

**Comment by julian-zucker** [comment]
I'm going to create three classes:

* `ModifierAgent` - rename current `MutatorAgent` to this
* `MutatorAgent` - a class that extends `ModifierAgent` and is an easy wrapper for one-to-one mutations. E.x. Bitflipper will be this. It will have a protected method `mutateOne` with signature `Solution => Solution`.
* `CrossoverAgent` a class that extends `ModifierAgent` for two-to-one mutations. For example, one point crossover. It will have a protected method `crossover` with signature `(Solution, Solution) => Solution`

These allow people to create any modifier they want, but it will be nice to have these convenience classes.
